# Loco yaml export: Simple YAML object
# Project: application.properties conversion
# Release: Working copy
# Locale: en-IN, English (India)
# Exported by: Unregistered user
# Exported at: Wed, 07 Nov 2018 17:30:59 +0530

spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost:3306/mysql
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver.class: com.mysql.jdbc.Driver
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
logging.level.org.hibernate.SQL: debug

